### ISSUE TITLE
Regarding Google Drive API!

### ISSUE THREAD

**Issue by NoorQureshi** [domsammut/GSA-JSON-Results-stylesheet#1]
Hi i need some help regarding google drive api. please add me on skype or email. skype: noorqureshics email: noorqureshics@gmail.com there's no contact page on your website.

**Comment by domsammut** [comment]
Hi,

I'm not available over to discuss this subject as it doesn't relate to this repository.

Thanks

**Comment by NoorQureshi** [comment]
but where should i contact you? if this repository isn't related? there's no way to contact you!

**Comment by domsammut** [comment]
Twitter is the best bet if it's not related to the repository. FYI I don't have any background or knowledge in working with the Google Drive API.
